export const posts = [
  {
    id: 1,
    title: "The insane Future of Web3",
    img: "https://images.pexels.com/photos/7963572/pexels-photo-7963572.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    desc: "Web3 can gain a lot of traction in the future with play-to-earn gaming. The massive surge in popularity of play-to-earn games such as Axie Infinity has shown the way forward for web3 gaming platforms. Decentralized storytelling would also emerge as one of the significant use cases of web3 in the future.",
    longDesc:
      "Web 3.0 is a concept for the next generation of the internet. It is the evolution of how users are able to control and own their creations and online content, digital assets and online identities.Web 2.0 is what we are experiencing at the moment. Companies develop and provide products and services in a centralized manner. Take Instagram as an example. Do you think you own your IG content? Nah, the company owns everything on the platform, and they have complete control of all the content that users create there. If they want to ban you or block you, they will do it.Another example is the popular online game Fortnite. Users have zero control over their in-game identities and assets that they “own”. In Web 2.0, users cannot control and monetize the content they create.In Web 3.0, however, users can create content while owning, controlling and monetizing them through the implementation of blockchain and cryptocurrencies. This is what enables NFTs. Am I sure you heard of it, right? Blockchain can enable users to interact with online services governed by peer-to-peer networks, which is essentially a decentralized network of computers instead of the server of a single entity. In such a setting, users can own their data and have permissionless and peer-to-peer transactions, bypassing middlemen's need for anyone with an internet connection and cryptocurrency wallets like Metamask. The full control of digital identities and how and when data are shared is therefore returned to users with different online applications through their private keys.",
  },
  {
    id: 2,
    title: "Benefits of reading books",
    img: "https://images.pexels.com/photos/1742370/pexels-photo-1742370.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    desc: "Reading is good for you because it improves your focus, memory, empathy, and communication skills. It can reduce stress, improve your mental health, and help you live longer. Reading also allows you to learn new things to help you succeed in your work.It is important to read a good book at least for a few minutes.",
    longDesc:
      "Reading is a very good habit that one needs to develop in life. Good books can inform you, enlighten you and lead you in the right direction. There is no better companion than a good book. Reading is important because it is good for your overall well-being. Once you start reading, you experience a whole new world. When you start loving the habit of reading you eventually get addicted to it. Reading develops language skills and vocabulary. Reading books is also a way to relax and reduce stress. It is important to read a good book at least for a few minutes each day to stretch the brain muscles for healthy functioning. Books really are your best friends as you can rely on them when you are bored, upset, depressed, lonely or annoyed. They will accompany you anytime you want them and enhance your mood. They share with you information and knowledge any time you need. Good books always guide you to the correct path in life. Following are the benefits of reading –Self Improvement: Reading helps you develop positive thinking. Reading is important because it develops your mind and gives you excessive knowledge and lessons of life. It helps you understand the world around you better. It keeps your mind active and enhances your creative ability.Communication Skills: Reading improves your vocabulary and develops your communication skills. It helps you learn how to use your language creatively. Not only does it improve your communication but it also makes you a better writer. Good communication is important in every aspect of life.",
  },
  {
    id: 3,
    title: "Importance of Fruits",
    img: "https://images.pexels.com/photos/1161547/pexels-photo-1161547.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    desc: "A diet rich in vegetables and fruits can lower blood pressure, reduce the risk of heart disease and stroke, lower risk of eye and digestive problems, and have a positive effect upon blood sugar, which can help keep appetite in check. Eating non-starchy vegetables and fruit may even promote weight loss.",
    longDesc:
      "Fruits are used as a complimentary for any meal. They can however be taken at any given time of the day because they have a long list of benefits to the body. Fruits are seasonal but this does not mean their consumption should be. It is paramount that fruits are incorporated profoundly in every diet.Roughage in the diet is important as it helps improve digestion and thereby preventing constipation. Children as well as adults experience constipation at any point of their lives making it ideal for both of them to take fruits on a regular basis.The constituents of fruits are also important in ensuring a healthy and soft skin. Fruits bring a glowing effect that is characteristic of a healthy skin. They do this because they have minerals that activate the dermal glands to keep the skin moisturized.Blood pressure is regulated by the ion concentrations in the blood. Potassium has a counter effect on the effect of sodium to cause high blood pressure. Intake of fruits rich in potassium will help manage blood pressure.Fruits do not have any cholesterol at all and this makes them very good when seeking weight loss. Science has proven that diet rich in fruit fiber has a role to play in weight loss without having to monitor calories.",
  },
];
